### ISSUE TITLE
Select before insert

### ISSUE THREAD

**Issue by AlexMAS** [ClickHouse/clickhouse-jdbc#1012]
Hello!

I'm trying to switch from `0.3.2-patch7` to `0.3.2-patch10` and at the same time replace the usage of `ru.yandex.clickhouse` with `com.clickhouse`.

I noticed before each `INSERT` you're trying to perform prefetch column types, for example here - [`ClickHouseConnectionImpl.getTableColumns()`](https://github.com/ClickHouse/clickhouse-jdbc/blob/v0.3.2-patch10/clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/ClickHouseConnectionImpl.java#L173). Yes, I investigated the code and understand the reason but is there ability to disable such behaviour? In that case you will use appropriate [`ClickHouseValue`](https://github.com/ClickHouse/clickhouse-jdbc/blob/master/clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseValue.java) implementations based on the provided parameters or a custom implementation of the `ClickHouseValue`. (For example, at the moment there is no ability to customize SQL representation for inserting values.)

Why I'm asking about that? Firstly, because I know the types of data being inserted and don't want extra interaction with the database.

Thanks

**Comment by zhicwu** [comment]
Hi @AlexMAS, if you know the types, can you use input function like below? This way, the driver will simply parse the query to get metadata, instead of using additional query.

```java
// create table mytable(id String, timestamp DateTime64(3), description Nullable(String)) engine=Memory

// 1. recommended as it performs the best
try (PreparedStatement ps = conn.prepareStatement(
    "insert into mytable select col1, col2 from input('col1 String, col2 DateTime64(3), col3 Int32')")) {
    // the column definition will be parsed so the driver knows there are 3 parameters: col1, col2 and col3
    ps.setString(1, "test"); // col1
    ps.setObject(2, LocalDateTime.now()); // col2, setTimestamp is slow and not recommended
    ps.setInt(3, 123); // col3
    ps.addBatch(); // parameters will be write into buffered stream immediately in binary format
    ...
    ps.executeBatch(); // stream everything on-hand into ClickHouse
}
```

**Comment by AlexMAS** [comment]
@zhicwu Thank you for reply. Yes, the `input()` function works well but to be honest the query syntax in this case is quite verbose. It'll be great if you mention about the `input()` function in the project readme/wiki.

Then another question. Are there other alternatives besides the `input()` function. As I understand, JDBC Driver is just a wrapper over Client API? And we can use it directly. What is recommended way to work with ClickHouse? Are there any conceptual benefits to use JDBC (in terms of performance and resource management)?

**Comment by zhicwu** [comment]
> Yes, the `input()` function works well but to be honest the query syntax in this case is quite verbose.

I agree. I wish ClickHouse supports prepared statement so that we don't have to do this.

> It'll be great if you mention about the `input()` function in the project readme/wiki.

There's examples for batch insert at [here](https://github.com/ClickHouse/clickhouse-jdbc/tree/master/clickhouse-jdbc#examples) but I guess it's hard to notice. Moving them to wiki is probably better.

> Are there other alternatives besides the `input()` function.

If the data volume is not huge and you don't mind to keep them in memory(on ClickHouse server), you may try [this](https://github.com/ClickHouse/clickhouse-jdbc/blob/ea5aaf579b0612bcf1825eb1ec31bf9b170a7a65/clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java#L946-L978) but it will only make things unnecessarily complex.

> As I understand, JDBC Driver is just a wrapper over Client API? And we can use it directly.

Yes, JDBC driver is a wrapper of Java client, and Java client hides implementation details like data format and protocol. Of course you can use Java client ([examples](https://github.com/ClickHouse/clickhouse-jdbc/tree/master/clickhouse-client)) or more native approach to access ClickHouse like [this](https://github.com/ClickHouse/clickhouse-jdbc/blob/ea5aaf579b0612bcf1825eb1ec31bf9b170a7a65/clickhouse-http-client/src/main/java/com/clickhouse/client/http/HttpUrlConnectionImpl.java#L203-L281). Alternatively, you can blend usage of JDBC and Java client, for instance: `statement.unwrap(ClickHouseRequest.class).query("select 1").executeAndWait()`, but it's not recommended because the code is no longer portable.

> What is recommended way to work with ClickHouse? Are there any conceptual benefits to use JDBC (in terms of performance and resource management)?

It depends. If you prefer stable API and may change to a different database in the future, you'd better stay with JDBC and avoid non-standard syntax in SQL queries. If performance is critical and you can tolerate API changes(before 0.4.0), it's encouraged to use Java client. Performance-wise, JDBC is slower and it uses more memory compare to Java client. Below is the result took from [here](https://github.com/go-faster/ch-bench#benchmarks).

`SELECT number FROM system.numbers_mt LIMIT 500000000`

Name | Time | RAM
-- | -- | -- 
curl (C, HTTP, no deserialization) | 3.7s | 10M
clickhouse-client (Java, HTTP) | 6.4s | 121M
clickhouse-jdbc (Java, HTTP) | 7.2s | 120M

**Comment by AlexMAS** [comment]
@zhicwu Thank you for so comprehensive reply! Probably the last question regarding Java Client API. How can I pass credentials (username and password)? I see overloads of the `ClickHouseNode.of()` but none of them accepts `ClickHouseCredentials`. Initially I expected something like this:

```java
var credentials = ClickHouseCredentials.fromUserAndPassword("user", "password");
var node = ClickHouseNode.of("https://localhost", credentials);
```

**Comment by AlexMAS** [comment]
Can I rely that the `ClickHouseClient` instance is thred-safe?

**Comment by zhicwu** [comment]
> How can I pass credentials (username and password)?

Yes, you can add credentials in ClickHouseNode using its builder function, which helps when you need to connect to multiple nodes using different credentials.  You can also set default credentials at client level, for example:

```java
ClickHouseClient client = ClickHouseClient.builder().defaultCredentials(...)...;
client.connect(<node>).query("select 1").executeAndWait();
```

> Can I rely that the ClickHouseClient instance is thred-safe?

Yes it's thread safe. However, you probably don't have to create many client instances. Instead, you may reuse the client instance and create multiple ClickHouseRequest for queries. ClickHouseRequest is not thread-safe as of now.
