### ISSUE TITLE
Has the copyright of clickhouse-jdbc changed?

### ISSUE THREAD

**Issue by wallace-clickhouse** [ClickHouse/clickhouse-jdbc#1026]
Has the copyright of clickhouse-jdbc changed from Yandex to ClickHouse Inc？
Thank you!

**Comment by zhicwu** [comment]
Hi @wallace-clickhouse, yes and the driver has been rewritten since v0.3.2 purely for technical reasons(decoupling, renaming package, and performance improvement etc.). Is there any concern since it's APL 2.0?

**Comment by wallace-clickhouse** [comment]
Thank you@zhicwu
I have no concern about APL 2.0,while I am wondering why and from which version the copyright was changed?If I use v0.3.2,is it exactly compatible for versions earlier than v20.7.

**Comment by zhicwu** [comment]
Sorry for the late response. Yes, it's changed since v0.3.2. However, as stated in README, v0.3.2 only supports ClickHouse 20.7+ and it's not a drop-in replacement of legacy driver(due to many changes around protocol and data format etc.).

As ClickHouse is evolving fast, you probably should consider to always upgrade the server to one of the [active releases](https://github.com/ClickHouse/ClickHouse/pulls?q=is%3Aopen+is%3Apr+label%3Arelease).
