### ISSUE TITLE
max_query_size URL parameter stopped working

### ISSUE THREAD

**Issue by konstantinosss** [ClickHouse/clickhouse-jdbc#1046]
We use max_query_size as JDBC URL parameter to increase allowed select query size:
`jdbc:clickhouse://ch-host:8123/db?max_query_size=1000000`

After switching from the deprecated package `ru.yandex.clickhouse` to the new one `com.clickhouse.jdbc` we discovered that this parameter is ignored and currently we have exceptions:

```
java.sql.BatchUpdateException: Code: 62. DB::Exception: Syntax error: failed at position 262144 ('86') (line 16, col 261384): 86. Max query size exceeded: '86'. (SYNTAX_ERROR) (version 21.12.3.32 (official build))
, server ClickHouseNode [uri=http://ch-host:8123/db, options={max_query_size=1000000,socket_timeout=30000,async=true,http_keep_alive=true}]@1448807023
	at com.clickhouse.jdbc.SqlExceptionUtils.batchUpdateError(SqlExceptionUtils.java:109)
	at com.clickhouse.jdbc.internal.SqlBasedPreparedStatement.executeAny(SqlBasedPreparedStatement.java:208)
	at com.clickhouse.jdbc.internal.SqlBasedPreparedStatement.executeQuery(SqlBasedPreparedStatement.java:235)
```

Position 262144 is related to the default limit of 256 KiB.

**Comment by zhicwu** [comment]
Hi @konstantinosss, you can add `custom_http_params` in connection property or url, for examples:
* connection property
  ```java
  Properties props = new Properties();
  // comma separated custom settings, you can add custom_http_headers in a similar way as well
  props.setProperty("custom_http_params", "session_check=0,max_query_size=1000");
  ```
* connection url
  ```java
  String url = "jdbc:clickhouse://ch-host:8123/db"
    // same as above but url encoded
    + "?custom_http_params=session_check%3D0%2Cmax_query_size%3D1000";
  ```

Sorry this is more of a workaround at this point because it's limited to http protocol. I'll add `custom_settings` to support more protocols.

**Comment by ilevd** [comment]
I have url string with such params:
```
/?socket_timeout=6000000&max_bytes_before_external_group_by=16000000000&optimize_aggregation_in_order=0&join_default_strictness=ANY&join_algorithm=auto&max_memory_usage=20000000000"
```
After switching from `ru.yandex.clickhouse 0.3.1` to  `0.3.2-patch11` these params don't work in all cases:
1. Using params in url connection string
2. Set every property individually and pass to ClickHouseDataSource
3. Set via `custom_http_params`

Checking with `SELECT * FROM system.settings`.  It returns e.g for `max_bytes_before_external_group_by` - value  `"0"` and changed `0` instead of `"16000000000"` and changed `1` when using old driver.

**Comment by zhicwu** [comment]
Hi @ilevd, will it work if you use `custom_settings` in latest nightly build at [here](https://s01.oss.sonatype.org/content/repositories/snapshots/com/clickhouse/clickhouse-jdbc/)? Feel free to open an issue if still not working.

https://github.com/ClickHouse/clickhouse-jdbc/blob/4d6fe526b38c1e8c64b50f871ca36c72c2c4e713/clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/internal/ClickHouseConnectionImplTest.java#L220-L221

**Comment by zhicwu** [comment]
> but I had to remove socket_timeout option and set it in url 

`socket_timeout` is not a server setting so you have to put it separately in connection string or properties.

> Am I right that all settings from [ClickHouse Settings](https://clickhouse.com/docs/en/operations/settings/settings/) should be in `custom_settings`?

Yes, maybe it should be renamed to `custom_server_settings` but it's getting too long to type in :p On a side note, if you have many settings to mange, you probably should consider to use server profile instead to benefit all type of clients instead of just JDBC.

> Or could you please explain when to use `custom_http_params`, `custom_settings` and ordinary properties? And are there plans to support all params in url string?

`custom_http_params` only works when using http protocol and it should support arbitrary parameter regardless it's a server setting or not. The driver will simply append the parameters to server url and then send http request accordingly. `custom_settings` on the other hand is more generic and it's also supported by other protocols like grpc and tcp. I think in most cases we should use `custom_settings`, but if you're using http and no plan to switch to any other protocol, you may use `custom_http_params` as well.

**Comment by ilevd** [comment]
@zhicwu, thanks!
