### ISSUE TITLE
Support configuring the socket options.

### ISSUE THREAD

**Issue by JackyWoo** [ClickHouse/clickhouse-jdbc#1139]
### Usage:

In my case I have 2 zones one for computation with Spark the other for result storage with ClickHouse and the bond width between the 2 zones is limited.

I have 2 task with different priorities and I want the hight priority task can transfer data without the effecting of the low priority task.

### Possible solution:

Support configuring the ip dscp. 

But `clickhouse-jdbc`  use `java.net.HttpURLConnection` which does support set socket options. 

Can somebody help?  /cc @zhicwu

**Comment by JackyWoo** [comment]
Maybe we will wait for `clickhouse-tcp-client`.

**Comment by zhicwu** [comment]
Hi @JackyWoo, sorry for the late reply.

You're right that HttpURLConnection does not support that, but HttpsURLConnection supports custom SSLSocketFactory, meaning we can implement the feature although it's limited to https.

As of today, we have two implementations in `clickhouse-http-client`, one is HttpURLConnection, and the other is HttpClient. I think we can add more using Apache Http Client and/or Okhttp to address the issue, but they might not work as stable as HttpURLConnection(due to the way they handle server closed socket). I thought about using Socket directly for http implementation, may it's still worthy of trying.

**Comment by JackyWoo** [comment]
It really help, thanks.
