### ISSUE TITLE
Result without columns

### ISSUE THREAD

**Issue by hashbash** [ClickHouse/clickhouse-jdbc#208]
Result without columns when query contains comments:

Query with no comments:
```
select * from `system`.processes
```
Result (only first columns):
```
is_initial_query |user    |query_id                             |
-----------------|--------|-------------------------------------|
0                |default |157cda81-6207-4f4f-b79f-de1ebc325f4a |
0                |default |3bd9aa79-8f03-4a15-a04a-2b756bf5df2c |
0                |default |8ec665c5-ce0c-4f04-b096-76e79cd71bb6 |
```

Query:
```
select * from `system`.processes
--where bgjksdbdfksjg
```
Result:
```
0 |default |dedb289b-8ecc-45c0-8891-7734e9bd3d7a |
--|--------|-------------------------------------|
0 |default |a95f5a5e-776b-4690-bfe3-3ec84497d217 |
0 |default |eaeaded5-5993-45b3-95fc-d4302a106f83 |
1 |default |61c2a108-3433-49d7-8d89-49927f47da9c |
1 |nginx   |d3e78d3c-48b2-4a45-8c19-efdcbfdfcfd7 |
```
I'm using DBeaver and latest JDBC-driver.

**Comment by serebrserg** [comment]
Thanks. The problem is quite clear - the driver adds FORMAT TabSeparatedWithNamesAndTypes at the end of the query with no regard to comments and in that case it is interpreted as a part of comment, so it is ignored.
The workaround is obvious - not using line comment at last line of a query. The fix is quite tricky - it needs either deeper query parsing or another way of passing format.

**Comment by den-crane** [comment]
But what if JDBC driver will add `\nFORMAT TabSeparatedWithNamesAndTypes`
