### ISSUE TITLE
Clickhouse & Pentaho

### ISSUE THREAD

**Issue by Qblolz** [ClickHouse/clickhouse-jdbc#213]
I have some question about jdbc
When i create connection in pentaho by `jdbc` - i can see tables and ect... but i dont see columns to create any relations.
Its problem jdbc or pentaho ?
In Pentaho logs talking about wrong types columns

**Comment by Astervinus** [comment]
Same for me. Are there any plans to finish this jdbc? We need it very much!

**Comment by blinkov** [comment]
Could you please provide more details on what exactly you are doing and which result is expected?

**Comment by picinato** [comment]
My problem when using Pentaho with Clickhouse are the ones needed in the commands.

Examples:

Step Update -> As most databases use standard sql and the normal update is update table set column = 'value' where filter = 'filter'  
But since the update in the clickhouse is alter table <table_name> update col = expr1 where <filter>

Is it possible in JDBC to create an interpreter? When does the standard command convert to the clickhouse command?

Thank you for your time.
Quilmer

**Comment by zhicwu** [comment]
SQL rewrite has been implemented in v0.3.2, this should have been fixed in latest releases. On a side note, Apache Hop is successor of Pentaho Kettle, and it has better integration with ClickHouse.
