### ISSUE TITLE
Reimplement parser of column structure

### ISSUE THREAD

**Issue by alex-krash** [ClickHouse/clickhouse-jdbc#386]
**Current situation**: parser functionality is not full. Missing support for Tuple() syntax.
**Goal**: support parsing of Tuple()
**Far goal**: allow to set tuples into prepared statement params.
**Very far goal**: support reading of tuples from resultset (when RowBinary protocol support is implemented)

**Comment by syominsergey** [comment]
@alex-krash Hello!
This is ineresting issue!
Could you please confirm my understanding, that tuples mentioned in this issue are structures described [here](https://clickhouse.yandex/docs/en/data_types/tuple/)?
What is definition of done for the first goal?
Could you describe in a free manner some test for the first goal, please?

**Comment by alex-krash** [comment]
@syominsergey , we need to have possibility to **read** Tuple(....) from resultset.
In JDBC standard there is an interface for such kind of structures: https://docs.oracle.com/javase/8/docs/api/java/sql/Struct.html
And here is one of implementations: https://github.com/housepower/ClickHouse-Native-JDBC/blob/fa6b1d3b543da9bd9934948f45ff984e61c8bf31/src/main/java/com/github/housepower/jdbc/ClickHouseStruct.java

We would like to support Tuples in the same manner.
It would be great if you implement it!

**Comment by syominsergey** [comment]
@alex-krash, thank you for links!
I will try to implement this.

Could you answer an another little question, please: in the [original issue description](https://github.com/ClickHouse/clickhouse-jdbc/issues/386#issue-490153181) reading tuples from result set was described as very far goal, when RowBinary protocol support is implemented. Is RowBinary protocol implementation really necessary for this goal? Or another ways possible?
And how about `Far goal: allow to set tuples into prepared statement params.`?

**Comment by alex-krash** [comment]
@syominsergey , sorry for late answer.
RowBinary protocol must be implemented at least for reading, because it gives significantly lower overhead on parsing response. But tuples support can be implemented without RowBinary protocol.
Implementation of Tuple support can be done in 2 steps:

1. Reading tuples from server - it has higher priority
2. Sending tuples to server - lower priority.

**Comment by syominsergey** [comment]
Alex, thank you exhaustive answer!9:21, 9 октября 2019 г., Alex Krash <notifications@github.com>:@syominsergey , sorry for late answer.
RowBinary protocol must be implemented at least for reading, because it gives significantly lower overhead on parsing response. But tuples support can be implemented without RowBinary protocol.
Implementation of Tuple support can be done in 2 steps:

Reading tuples from server - it has higher priority
Sending tuples to server - lower priority.

**Comment by syominsergey** [comment]
I'm trying to implement reading tuples without row binary protocol.
Here is PR. It is just for information, because work is not finished.
https://github.com/ClickHouse/clickhouse-jdbc/pull/399
I have implemented recursive parsing of column description for tuples. The next steps:
- recursively parse column values for tuples
- write tests

**Comment by zhicwu** [comment]
Since 0.3.2, `RowBinary` became the default data format. `com.clickhouse.client.ClickHouseColumn` was added with the ability of parsing relatively complex column definition including tuple, nested, and mixed use of them(e.g. array of tuple etc.). Tuple and AggregateFunction(just bitmap at this point) can be set in prepared statement and get from result set.
