### ISSUE TITLE
Date literal issue in the JDBC driver

### ISSUE THREAD

**Issue by bas-ter** [ClickHouse/clickhouse-jdbc#457]
Hi, I'm using clickhouse-jdbc driver in the Oracle Bi server environment and it works perfectly except the one thing. The JDBC driver doesn't support date literals in SQL statements written in the format:
{d 'yyyy-mm-dd'} where yyyy-mm-dd represents the year, month, and day; for example, {d '1998-10-22'}.
Is there any way to add this functionality to the clickhouse-jdbc driver? 
Or as a workaround is it possible to duplicate an existing function "todate" with the same name as it is in Oracle "to_date"?

Thank you in advance.

**Comment by zhicwu** [comment]
This was supported since 0.3.2-test2, but just some very basic ones:
  * `{d '2021-11-01'}` -> `date'2021-11-01'`
  * `{t '12:34:56'}` -> `timestamp'1970-01-01 12:34:56'`
  * `{ts '2021-11-01 12:34:56'}` -> `timestamp'2021-11-01 12:34:56'`
  * `{ts '2021-11-01 12:34:56.78'}` -> `toDateTime64('2021-11-01 12:34:56.78', 2)`
  * `{tt 'my_temp\'_''table'}` -> ``` `my_temp'_'table` ```
      Note: `tt` is short for **t**emporary **t**able. It's a hint for using external table or creating a session-level temporary table.
