### ISSUE TITLE
Any plans on adding support for r2dbc spec

### ISSUE THREAD

**Issue by meshpaul** [ClickHouse/clickhouse-jdbc#477]
Hello,

   Any plans on adding support for[ r2dbc spec](https://github.com/r2dbc/r2dbc-spi) I think this is next evolution of DB connectivity

I think your driver already exposes some of these concepts.   

Thank you.

**Comment by joschi** [comment]
@meshpaul Do you think the MySQL interface together with https://github.com/mirromutth/r2dbc-mysql could be used for this?

**Comment by smagellan** [comment]
term "next evolution" may be problematic: https://twitter.com/jodastephen/status/1176186251277471747

**Comment by joschi** [comment]
> term "next evolution" may be problematic: [twitter.com/jodastephen/status/1176186251277471747](https://twitter.com/jodastephen/status/1176186251277471747)

@smagellan That tweet was about the [Asynchronous Database Access API (ADBA)](https://blogs.oracle.com/java/jdbc-next%3a-a-new-asynchronous-api-for-connecting-to-a-database) project by Oracle, not R2DBC.

Also note that Oracle just released the official (!) [R2DBC (!!) Driver for Oracle Database](https://github.com/oracle/oracle-r2dbc) and even made it [available on Maven Central (!!!)](https://search.maven.org/artifact/com.oracle.database.r2dbc/oracle-r2dbc/0.1.0/jar), so I wouldn't exactly assume that R2DBC isn't a good candidate for implementation in a database driver. 😉

**Comment by smagellan** [comment]
@joschi Interesting, thank you

**Comment by zhicwu** [comment]
Thanks everyone for sharing your thoughts on this. However, I'd not suggest to simply build an adapter to bridge async calls to the JDBC driver.

There's a diagram in #570 illustrates the whole structure. Basically, in order to implement r2dbc driver, we need to:
* implement `clickhouse-client` and `clickhouse-http-client`/`clickhouse-grpc-client`/`clickhouse-native-client` first
  Note: `clickhouse-jdbc` will be refactored to use `clickhouse-client`.
* and then work on `clickhouse-r2dbc` by leveraging `clickhouse-client`(and optionally http/grpc/native providers)

I'm working on `clickhouse-client` and `clickhouse-http-client`, which will be available in 0.3.1. `clickhouse-gprc-client` can be generated quickly, so it will be added soon. I believe we can start to work on `clickhouse-r2dbc` in 0.4.0 or 0.3.2. In case you need a quick workaround, please consider mysql/postgresql interface as @joschi suggested.

**Comment by sneakythr0ws** [comment]
Has anyone tried mysql interface for https://github.com/mirromutth/r2dbc-mysql?
Seems like this bundle doesn't work together. 
I tried and had a problem
```
Caused by: java.lang.IllegalArgumentException: Cannot decode value of type class java.lang.String for 3 with collation 63
	at dev.miku.r2dbc.mysql.codec.DefaultCodecs.decodeNormal(DefaultCodecs.java:212) ~[r2dbc-mysql-0.8.2.RELEASE.jar:0.8.2.RELEASE]
	at dev.miku.r2dbc.mysql.codec.DefaultCodecs.decode(DefaultCodecs.java:105) ~[r2dbc-mysql-0.8.2.RELEASE.jar:0.8.2.RELEASE]
	at dev.miku.r2dbc.mysql.MySqlRow.get(MySqlRow.java:59) ~[r2dbc-mysql-0.8.2.RELEASE.jar:0.8.2.RELEASE]
	at dev.miku.r2dbc.mysql.MySqlConnection.lambda$null$3(MySqlConnection.java:86) ~[r2dbc-mysql-0.8.2.RELEASE.jar:0.8.2.RELEASE]
	at dev.miku.r2dbc.mysql.MySqlResult.processRow(MySqlResult.java:176) ~[r2dbc-mysql-0.8.2.RELEASE.jar:0.8.2.RELEASE]
	at dev.miku.r2dbc.mysql.MySqlResult.handleResult(MySqlResult.java:149) ~[r2dbc-mysql-0.8.2.RELEASE.jar:0.8.2.RELEASE]
	at dev.miku.r2dbc.mysql.MySqlResult.lambda$map$1(MySqlResult.java:93) ~[r2dbc-mysql-0.8.2.RELEASE.jar:0.8.2.RELEASE]
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:102) ~[reactor-core-3.4.5.jar:3.4.5]
	... 51 common frames omitted
```
As I understand [this is the same issue](https://github.com/mirromutth/r2dbc-mysql/issues/177)

**Comment by zhicwu** [comment]
Now we have `clickhouse-client`, a semi-async library supporting both http and grpc. Would be great if anyone is interested to start a PR or new repo for `clickhouse-r2dbc` :)

**Comment by linghengqian** [comment]
Just confused, doesn't https://github.com/ClickHouse/clickhouse-jdbc/pull/914 solve this issue?  Why is this issue not closed?

**Comment by zhicwu** [comment]
Hi @linghengqian, it's because I haven't test the r2dbc driver yet. I just quickly went over the code, added a few feedback along with some quick fixes.

Among all the issues I mentioned [here](https://github.com/ClickHouse/clickhouse-jdbc/pull/914#pullrequestreview-1103194556), my biggest concerns are 1) lack of testing; 2) potential resource leaking(closing ClickHouseResponse etc.), and 3) exception handling. Actually I'm not quite sure about the last two, as I'm not familiar with r2dbc spec. Having said that, I think @rernas35 did great job creating the new module and I wouldn't mind to release what we have as part of v0.3.3 :)

Now we have nightly build at [here](https://s01.oss.sonatype.org/content/repositories/snapshots/com/clickhouse/clickhouse-r2dbc/), can someone please give it a shot and comment here? Any pull request is greatly appreciated :)

**Comment by kyleloomis** [comment]
I tested the nightly build and I am running into two issues: Dialect and Package Version.

# Issue with Dialect
The database configuration requires an `R2dbcDialect`. Error:

```
Factory method 'r2dbcCustomConversions' threw exception; nested exception is org.springframework.data.r2dbc.dialect.DialectResolver$NoDialectException: Cannot determine a dialect for ClickHouse using com.clickhouse.r2dbc.connection.ClickHouseConnectionFactory@7c70aae1. Please provide a Dialect.
```

I am configuring the client using `AbstractR2dbcConfiguration`

```kotlin
@Configuration
@EnableR2dbcRepositories(
    basePackages = ["com.base.repository.clickhouse"],
    databaseClientRef = "data"
)
class ClickhouseDBConfig(private val databaseCredentials: DatabaseCredentials) : AbstractR2dbcConfiguration() {
    override fun connectionFactory(): ConnectionFactory {
        return ConnectionFactories.get(databaseCredentials.CLICKHOUSE)
    }

    @Bean(name = ["data"])
    fun client(): DatabaseClient {
        val factory = connectionFactory()

        return DatabaseClient
            .builder()
            .bindMarkers(getDialect(factory).bindMarkersFactory)
            .connectionFactory(factory)
            .build()
    }
}
```

I am able to solve this issue by overriding the `getDialect` method available inside of `AbstractR2dbcConfiguration`.

```kotlin
override fun getDialect(connectionFactory: ConnectionFactory): R2dbcDialect {
    return MySqlDialect() # TODO replace with custom dialect
}
```

I am currently returning `MySqlDialect()` above (just for testing) and it seems be working. I believe we need to create a base dialect available inside of the R2DBC package.


# Version Conflicts
There seems to be a conflict between the `r2dbc-spi` version when using both the `clickhouse-r2dbc` and `org.springframework:spring-r2dbc:5.3.21` packages. When importing `org.springframework:spring-r2dbc:5.3.21`, it sets the `r2dbc-spi` version to `0.9.1.RELEASE`. In this version, the `RowMetadata` interface has a deprecated `getColumnNames` method. If we use this default version of `r2dbc-spi`, then it fails because `ClickHouseRowMetadata` doesn't implement `getColumnNames`.

Alternatively, if I force the `r2dbc-spi` to be the version specified in `clickhouse-r2dbc` (`1.0.0.RELEASE`), then there is an error in the r2dbc core `ColumnMapRowMapper` class because `getColumnNames` no longer exists.

Since I imagine a lot of users will be using the package `org.springframework:spring-r2dbc:5.3.21`, I would recommend downgrading the `r2dbc-spi` version to be `0.9.1.RELEASE` and implementing the `getColumnNames` inside of `ClickHouseRowMetadata`, at least until the spring-r2dbc package catches up to use the newest spi version.

**Comment by linghengqian** [comment]
@kyleloomis Why do we need to fall back to R2DBC SPI 0.9.1.RELEASE? This is unreasonable, because at https://github.com/spring-projects/spring-framework/issues/28787, spring-r2dbc has been promoted to R2DBC 1.0.0-RELEASE and no one in the R2DBC community is maintaining R2DBC R2DBC driver for SPI 0.9.1.RELEASE.

**Comment by zhicwu** [comment]
Thanks for the feedback @kyleloomis. Dialect is defined in Spring so it's not suitable to add it into r2dbc driver. As to version conflict, since r2dbc 0.9.1 is very close to 1.0.0, I created #1094 to support that. 0.8.x  is probably too old and not worthy to support.

```xml
<dependency>
    <groupId>com.clickhouse</groupId>
    <artifactId>clickhouse-r2dbc_0.9.1</artifactId>
    <version>0.3.3-SNAPSHOT</version>
</dependency>
```

**Comment by meshpaul** [comment]
> Thanks everyone for sharing your thoughts on this. However, I'd not suggest to simply build an adapter to bridge async calls to the JDBC driver.
> 
> There's a diagram in #570 illustrates the whole structure. Basically, in order to implement r2dbc driver, we need to:
> 
>     * implement `clickhouse-client` and `clickhouse-http-client`/`clickhouse-grpc-client`/`clickhouse-native-client` first
>       Note: `clickhouse-jdbc` will be refactored to use `clickhouse-client`.
> 
>     * and then work on `clickhouse-r2dbc` by leveraging `clickhouse-client`(and optionally http/grpc/native providers)
> 
> 
> I'm working on `clickhouse-client` and `clickhouse-http-client`, which will be available in 0.3.1. `clickhouse-gprc-client` can be generated quickly, so it will be added soon. I believe we can start to work on `clickhouse-r2dbc` in 0.4.0 or 0.3.2. In case you need a quick workaround, please consider mysql/postgresql interface as @joschi suggested.

The  original driver supports HTTP.  In todays cloud protocols should CH  R2DBC should support as bare minimum HTTP protocol IMHO

**Comment by zhicwu** [comment]
> The original driver supports HTTP. In todays cloud protocols should CH R2DBC should support as bare minimum HTTP protocol IMHO

Sorry I missed this one. @meshpaul, have you tried the nightly build? You can use -http jar like [this](https://s01.oss.sonatype.org/content/repositories/snapshots/com/clickhouse/clickhouse-r2dbc/0.3.3-SNAPSHOT/clickhouse-r2dbc-0.3.3-20221129.155737-63-http.jar), which only contains http support.

**Comment by meshpaul** [comment]
Thanks we will try

**Comment by meshpaul** [comment]
And I also like gRPC as well approach will let you know

**Comment by zhicwu** [comment]
Like JDBC driver, there are 3 classifiers you can choose: `all`(CLI + gRPC + HTTP), `grpc`, and `http`.
