### ISSUE TITLE
Show the hosts where the query was executed successfuly in JDBC driver

### ISSUE THREAD

**Issue by Solanj** [ClickHouse/clickhouse-jdbc#484]
Client already does that but the driver doesn't.
It is needed to act adequately when some of the hosts are down, for example. And checking each host manually to know if the query was a success there seems woefully inefficient.

Thank you.

**Comment by zhicwu** [comment]
Since #1008, the error message was changed to something like below, which provides enough details for troubleshooting. Server display name will be added in the future (as part of #691?).

`Code: <code>, DB::Exception: <server error message>, server ClickHouseNode [uri=<protocol>://<host>:<port>/<db>, options={...}]@<hash>`
