### ISSUE TITLE
Failed to parse the given SQL

### ISSUE THREAD

**Issue by Okapist** [ClickHouse/clickhouse-jdbc#614]
`` desc table t1 as `t2` ``

This sql is valid.

**Comment by Okapist** [comment]
Please backport fix to 2.x release

**Comment by zhicwu** [comment]
Thank you @Okapist for reporting the issue. It's a bit surprising that alias can be used in desc statement :p

I'll create PR to fix this in 0.3.1, but I think we probably don't need to backport the fix to 0.2.x, because it's just a warning and the query will be sent to server anyway. Let me know if you think backport helps at your end.

**Comment by Okapist** [comment]
We have a lot of this statements and it's generate a lot of unnecessary logs.
I saw in Roadmap that 3.x branch is technical and better to wait for 4.x. This is to long.

**Comment by zhicwu** [comment]
I see. There are two approaches to get rid of the annoying warnings: 1) increase log level to ERROR or at least do that for ClickhouseSqlParser; 2) change connection string by adding `use_new_parser=false`.

I'll backport the fix to 0.2.x branch and create a snapshot package.

**Comment by zhicwu** [comment]
@Okapist, you may check out code from 0.2.x branch and use `mvn -DskipTests clean package` to generate new package for the fix.
