### ISSUE TITLE
Is it possible to batch update table

### ISSUE THREAD

**Issue by luoyuxia** [ClickHouse/clickhouse-jdbc#630]
Currently, the clickhouse-jdbc doesn't support batch update table. 
I wonder is it possible to modify clickhouse-jdbc to make it support the  batch update. 
if so, what's the best or elegant way to do that.
Should I send 'alter' statement one by one to clickhouse server in a batch?

**Comment by zhicwu** [comment]
Yes, batch processing is limited to insert at this point, because update and delete are too heavy and they're not recommended to use frequently. There's a light-weight version(see ClickHouse/ClickHouse#19627) under discussion, but it takes time to implement.

Anyway, I'm working on #296 which will resolve this - it's nothing special but executing statements one by one in synchronous mode.

**Comment by luoyuxia** [comment]
Thank you for your reply!

**Comment by zhicwu** [comment]
> I have another question, does synchronous mode is necessary?

It's not. Sorry I wasn't clear on this. It's controlled by [mutations_sync](https://clickhouse.tech/docs/en/operations/settings/settings/#mutations_sync), which defaults to 0(async) as in ClickHouse server. In a typical ELT scenario, you may want to enable synchronous mutation so that you can update something first and then query against the updated rows.

> I mean when the mutations_sync = 0 (Mutations execute asynchronously), if first update a = 1 where c = 2. and then second update a = 3 where c = 2. what's the eventually value of a? Can it guarantee eventually consistent?

I'm not sure about implementation details like how it handles concurrent mutations(seems version-based), whether used a queue to serialize expensive operations or not, and of course its eventual consistency. I saw a similar question at ClickHouse/ClickHouse#23180 but no one answered. Perhaps you can ask the question on Telegram/Slack?

**Comment by luoyuxia** [comment]
Thank you very much!
