### ISSUE TITLE
setUseServerTimeZone setUseTimeZone don't not work anymore

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/clickhouse-jdbc#680]
Probably they should be removed, they do nothing now.

```java
    public static void main(String[] args) throws SQLException {
        ClickHouseProperties properties = new ClickHouseProperties();
        properties.setUseServerTimeZone(false);
        properties.setUseTimeZone("Canada/Atlantic");  // my desktop's timezone

        ClickHouseDataSource dataSource = new ClickHouseDataSource("jdbc:clickhouse://localhost:8123/", properties);

        ClickHouseConnection   connection = dataSource.getConnection();

        ResultSet rs = connection.createStatement().executeQuery("SELECT toDateTime('2020-01-01 00:00:00') t, toString(t) AS ts, timezone() z");
        rs.next();
        System.out.println(rs.getObject("t"));
        System.out.println(rs.getObject("ts"));
        System.out.println(rs.getObject("z"));
    }
```

```
<version>0.2.6</version>
2020-01-01 00:00:00.0
2020-01-01 00:00:00
UTC
```

```
<version>0.3.1</version>
2019-12-31 20:00:00.0
2020-01-01 00:00:00
UTC
```

-----------

```
     properties.setUseTimeZone("Europe/Moscow");

<version>0.2.6</version>
2019-12-31 17:00:00.0
2020-01-01 00:00:00
UTC

<version>0.3.1</version>
2019-12-31 20:00:00.0
2020-01-01 00:00:00
UTC
```

**Comment by zhicwu** [comment]
Thanks @den-crane. I have to admit that the driver is really buggy on handling timezone. Now I'm in the middle of building new JDBC driver using grpc(for testing purpose), and then I'll tackle this by replacing underlying format to RowBinary.

Put the inconsistent results aside, I think it's more important to ask what's the expectation. Based on my understanding, the result should be consistent with `clickhouse-client` - actually 0.3.1 returned correct result for the first case but failed for the second. However, it's just my opinion, since timezone only affects string representation of a timestamp, so `toDateTime('2020-01-01 00:00:00')` should be really treated as `toDateTime('2020-01-01 00:00:00', 'Canada/Atlantic')` in the first case.

I'd suggest to keep the properties as some of the users may still need the feature(some day not today ;). We probably should remove `useServerTimeZone` and `useServerTimeZoneForDates` while only keep `useTimeZone`.

**Comment by zhicwu** [comment]
In 0.3.2:

* use_server_time_zone=false, use_time_zone=Canada/Atlantic
  2019-12-31 20:00:00	2020-01-01 00:00:00	UTC
  
* use_server_time_zone=false, use_time_zone=Europe/Moscow
  2020-01-01 03:00:00	2020-01-01 00:00:00	UTC

* use_server_time_zone=false, use_time_zone=America/Los_Angeles
  2019-12-31 16:00:00	2020-01-01 00:00:00	UTC

If you use DBeaver etc. for the test, after changing connection property, you'd better invalidate the connection or it may still using the cached time zone.
