### ISSUE TITLE
Why package com.clickhouse.client.grpc.impl isn't in master branch?

### ISSUE THREAD

**Issue by DF5HSE** [ClickHouse/clickhouse-jdbc#799]
I forked repository, cloned it, opened project in IDEA and tried to launch tests from [clickhouse-jdbc/src/test/java/com/clickhouse/jdbc](https://github.com/ClickHouse/clickhouse-jdbc/tree/master/clickhouse-jdbc/src/test/java/com/clickhouse/jdbc) by clicking green triangle near tests in IDEA.

The IDEA starts building and fails with error
`java: package com.clickhouse.client.grpc.impl does not exist`
in files, which are importing this package. For example, this package is imported in [clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/ClickHouseStreamObserver.java](https://github.com/ClickHouse/clickhouse-jdbc/blob/master/clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/ClickHouseStreamObserver.java#L17)

There is no `impl` package in repository. The only mention of `impl` package I found on [jar-download.com](https://jar-download.com/artifacts/com.clickhouse/clickhouse-grpc-client/0.3.2/source-code), but downloading source code of `impl` package and storing it in `com/clickhouse/client/grpc` led to more compilation errors.

How can I launch tests and why package `com.clickhouse.client.grpc.impl` isn't in master branch

P.S. I want to implement specifying multiple hosts in connection URL and connection to alive host. That is why I need to launch tests for checking, if I broke something.

**Comment by zhicwu** [comment]
Thanks @DF5HSE. Are you going to re-write `ClickHouseCluster`? It's planned in next release(0.3.3) but haven't started yet. Do you want to take it over? With that and basic support for most common load balancing policies like round-robin and first-alive etc., JDBC connection URL can be enhanced to support multiple URLs. In addition, you may want to check system tables so that user does not have to specify all nodes of a cluster in the URL manually.

Anyway, back to your question. Those are generated code, so we don't commit them into git. If you're using maven, issue `mvn -Drelease clean compile` in `clickhouse-grpc-client` will generate the code in `target/generated-sources` directory. I use VS Code for development and it works well in most of time. You may need to install gRPC plugins if you use some other IDEs.

**Comment by DF5HSE** [comment]
Thank you for answer. I've tried to generate this code last hours, but haven't achieved success. Issue from your comment fails with error:
```
clickhouse-jdbc/clickhouse-grpc-client$ mvn -Drelease clean compile
[ERROR] Error executing Maven.
[ERROR] java.lang.IllegalStateException: Unable to load cache item
[ERROR] Caused by: Unable to load cache item
[ERROR] Caused by: Could not initialize class com.google.inject.internal.cglib.core.$MethodWrapper
```
I will try to something and hope tests will be able to lauch.

As for multiple hosts. I am engaged in research work at the university. Its gold is adding opportunity to connect to one of giving ClickHouse hosts in main ClickHouse interfaces. I have already implemented it in command-line client and in C++ client library.
The next place, where I wanted to add mupltiple host setting, became JDBC-driver. In JDBC-driver setting multiple hosts can work like this: user creat `ClickHouseDataSource`, where he set URL like `jdbc:ch//host1:port1,host2:port2,hostN:portN/...`. And after that user can work with DataSource as he worked before.

Last days I am researching code. I've thought, that I need to implement round-robin in `ClickHouseConnectionImpl` by writing cycle, where I would call `client.ping(node)` and choosing available one. After reading your comment I understood, that my solution isn't optimal, because there is a `ClickHouseCluster` class.

That is why I didn't want to re-write `ClickHouseCluster`. And I don't think, that I can do this correct according to my little experience in development of database management systems.

I read your [comment](https://github.com/ClickHouse/clickhouse-jdbc/issues/784#issuecomment-1003545540) about re-writing `ClickHouseCluster` and I have a question: can I use `ClickHouseCluster` for implementing multiple hosts in JDBC-driver? I am afraid that `ClickHouseCluster` interface can be changed in the future and it will be better not to use `ClickHouseCluster` now. And more common question: does it make sense to implement setting multiple hosts in JDBC-driver now? May be it will be better to add this functionality after re-writing `ClickHouseCluster`.

**Comment by zhicwu** [comment]
What will you get if you run `mvn -version`? I use Maven 3.8 and JDK 11 and sometimes docker images like `maven:3.8-eclipse-temurin-11`.

> URL like `jdbc:ch//host1:port1,host2:port2,hostN:portN/...`

Looks good. Instead of making changes to ClickHouseConnectionImpl, you may start with a new DataSource class. Also please be aware that, as of now, `jdbc:ch://` is interpreted as `jdbc:clickhouse:http://`, which is not always true. In next release, the driver will [probe](https://github.com/ClickHouse/clickhouse-jdbc/blob/63a870c50ac1c93d70ecff6e36a4b949624288f6/clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseCluster.java#L165) each endpoint and hopefully choose proper protocol(one of http, grpc and tcp) accordingly.

> can I use ClickHouseCluster for implementing multiple hosts in JDBC-driver?

You don't have to rely on it for now. You can take the ping approach along with a new DataSource class(and maybe extended Connection class as well).

> does it make sense to implement setting multiple hosts in JDBC-driver now?

I think so. But it's up to you whether to hold until ClickHouseCluster(or ClickHouseNodes) is ready.

**Comment by DF5HSE** [comment]
> What will you get if you run mvn -version?

Maven is 3.6 and JDK 17. I'll try to update Maven and use JDK 11, may be it will fix all errors.

The rest I will try to create a new DataSource class with mupltiple host support and create a PR when I finish.

Do I understand correctly that in case of success we will merge current `ClickHouseDataSource` class and mine?

**Comment by zhicwu** [comment]
> Do I understand correctly that in case of success we will merge current `ClickHouseDataSource` class and mine?

Yes and looking forward to your PR. Please also add unit tests to prove it's working.

**Comment by DF5HSE** [comment]
Ok

**Comment by zhicwu** [comment]
Close this one - we can discuss `ClickHouseDataSource` enhancement in #894.
