### ISSUE TITLE
recommendations for using the jdbc client for query large result？

### ISSUE THREAD

**Issue by jr981008** [ClickHouse/clickhouse-jdbc#803]
Are there recommendations for using the jdbc client for query large result(more than 100 million results), 
like cursors or partitions, can jdbc accomplish such tasks, how about performance,thanks for your suggestion

**Comment by zhicwu** [comment]
I can only think of timeout settings, for examples: socket timeout and max execution time etc. Starting from 0.3.2, JDBC driver no longer holds too much data in memory, so I'd not worry about rows to process. However, we may have issue dealing with large tuple/array/map. Apart from that, the driver does not support AggregateFunction - you may have to convert the state to either string or array.

There's no cursor or partition on client side, it's up to you whether to split the query into smaller ones running in parallel, but please keep in mind that it may cause more memory and CPU usage on server side too.

**Comment by asasas234** [comment]
@zhicwu 
I also encountered the same problem, if there is no cursor, what can clickhouse do to achieve efficient paging?

**Comment by zhicwu** [comment]
> @zhicwu I also encountered the same problem, if there is no cursor, what can clickhouse do to achieve efficient paging?

Sorry for the late response @asasas234. If you're talking about JDBC driver, due to its limited API, you have to repeat the same trick for mysql to use one SQL to count rows and the other for pagination using `limit` and `offset`. If you don't mind to use Java client, you can pass `send_progress_in_http_headers=1` and get row count(`total_rows_to_read`) and selected rows in one query([example](https://github.com/ClickHouse/clickhouse-jdbc/blob/425bb857dcb85dd482c6de0bf105ff750b59a1e6/clickhouse-http-client/src/test/java/com/clickhouse/client/http/ClickHouseHttpClientTest.java#L59)). Alternatively, you can mix usage of JDBC and Java client, for example: `statement.unwrap(ClickHouseRequest).set("send_progress_in_http_headers", 1).query(...).executeAndWait().getSummary().getTotalRowsToRead()`. Behind the scene, it's something like `curl -v 'http://localhost:8123/?query=select+*+from+numbers(1000000000000)+limit+100,100&send_progress_in_http_headers=1'`.
