### ISSUE TITLE
Is the driver fully jdbc compliant?

### ISSUE THREAD

**Issue by mjhamm75** [ClickHouse/clickhouse-jdbc#849]
I am trying to use `NamedParameterJdbcTemplate` and the driver is not interpolating the query arguments into the query string. Here is a StackOverflow describing what is going on.

https://stackoverflow.com/questions/71314115/why-are-namedjdbctemplate-not-working-with-clickhouse-jdbc?noredirect=1#comment126068476_71314115

What am I getting wrong?

**Comment by zhicwu** [comment]
> Parameter index must between 1 and 0 but we got 1

The error message is confusing and I really need to make it clear. Anyway, it meant no parameter found in the query. 

Can you remove `properties.setProperty("namedParameter", "true")` and try again? The property is used to enable named parameter support(instead of JDBC style `?` placeholders) in JDBC API. `NamedParameterJdbcTemplate` is an extended wrapper to substitute named parameters to `?` placeholders so they won't work together.

As to your question, the driver is not fully JDBC compliant although we tried to make it as close as enough. That's why there's fake transaction support even though ClickHouse does not.

**Comment by zhicwu** [comment]
Feel free to reopen if the issue remains.

**Comment by pkoosha** [comment]
Can you please update me if this issue is resolved? We have an application that uses springboot + mysql jdbc. I have been trying to migrate to clickhouse in a labor saving manner. However, I cannot find if the clickhouse-jdbc is compatible with rowMapper (org.springframework.jdbc.core.RowMapper;) and NamedParameterJdbcTemplate can I use clickhouse jdbc?

**Comment by zhicwu** [comment]
Hi @pkoosha, did you run into specific issue using the JDBC driver? `NamedParameterJdbcTemplate` should work but I haven't tried `RowMapper`.

**Comment by MatthewLieber** [comment]
@zhicwu I am testing something with the NamedParameterJdbcTemplate and it seems like it creates a prepared statement which is not supported through the mysql interface.  Can you please confirm if NamedParameterJdbcTemplate is supported?

**Comment by fubai** [comment]
I got the same error if the paramter value contains a colon
