### ISSUE TITLE
Array of string was not implemented?

### ISSUE THREAD

**Issue by eugeniasimich** [ClickHouse/clickhouse-jdbc#850]
We migrated to the new driver and we're getting ```java.lang.IllegalArgumentException: Only singleton array is allowed```. I checked the repo and see that Array of numbers was implemented but not array of other stuff. Am I right? Is there a way to overcome this error?

**Comment by zhicwu** [comment]
Both `select ['a','b']::Array(String)` and `select [('a'),('b')]::Array(Tuple(String))` work for me.

Could you please provide some more information like version of the driver and steps to reproduce the issue? If you have code snippet(SQL/Java) for reproducing that would be even better.

**Comment by eugeniasimich** [comment]
Sure!
We're using "0.3.2-patch5" version of jdbc, client, http-client 
We have a table in CH with a field of type Array(String) and we're trying to insert into it. 

(Code is in scala, we use doobie library, we implemented our own doobie `Put` instance, but also checked with postgres instance and implicit converters and it fails the exact same way)

This is the error we're getting
```
java.lang.IllegalArgumentException: Only singleton array is allowed, but we got: [user-agent: http4s-blaze/0.15.2, X-Forwarded-For: 127.0.0.3]
	at com.clickhouse.client.ClickHouseValue.update(ClickHouseValue.java:1148)
	at com.clickhouse.jdbc.ClickHouseConnection.createArrayOf(ClickHouseConnection.java:40)
	at com.clickhouse.jdbc.ClickHouseConnection.createArrayOf(ClickHouseConnection.java:23)
	at com.zaxxer.hikari.pool.HikariProxyConnection.createArrayOf(HikariProxyConnection.java)
```

**Comment by zhicwu** [comment]
> I checked the repo and see that Array of numbers was implemented but not array of other stuff.

Unlike array of primitives, array of String is simply treated as Object. That's why there's no update(String[]) method in ClickHouseValue class and it's not handled specifically in update(Object).

> We have a table in CH with a field of type Array(String) and we're trying to insert into it.

I see. I assume that you're using `PreparedStatement` for batch insert.

If that's the case, could you please use input function as shown in [examples](https://github.com/ClickHouse/clickhouse-jdbc/tree/master/clickhouse-jdbc#examples)? To be more specific, instead of `insert into mytable values(?,?,?)`, use `insert into mytable select col1, col2, col3 from input('col1 String, col2 DateTime64(3), col3 Array(String)')`, or `insert into mytable` for convenience. The differences are:
1) the first query has no type information so the driver has to "guess" based on type of given parameters, and worse than that, the driver will generate a large SQL statement like `insert into table values(...)(...)...` and send it to server
2) the last two provide type information needed by the driver, so it can take care of type conversion automatically and stream the data(in binary format) to the server, which is usually faster with less memory usage(on client side) and network traffic

Meanwhile, since there'll be another patch release this weekend. I'll see if I can enhance the driver accordingly.

**Comment by zhicwu** [comment]
Starting from `0.3.2-patch6`, `insert into table(col1,col2,col3) values(?,?,?)` is treated as `insert into table(col1,col2,col3)`(streaming instead of sending large SQL with values expression). `select col1,col2,col3 from table where 0` will be issued for type inferring when creating PreparedStatement. This means you no longer has to change code by switching to input function.

However, the implementation is naive as it will still build large SQL for cases like `insert into table(col1,col2,col3) values(? + 0,?,?)`.

**Comment by zheyu001** [comment]
If using `insert into mytable select col1, col2, col3 from input('col1 String, col2 DateTime64(3), col3 Array(String)`, do I still need to use
```
ps.setString(1, "test"); 
ps.setInt(3, 123); 
```
?

Can I just use ps.setObject(index, obj) for any types of data for simplicity? And can ps.setObject(index, obj) handle String[] correctly in this case?

**Comment by zheyu001** [comment]
Besides why only 1 element array is allowed as shown [here](https://github.com/ClickHouse/clickhouse-jdbc/blame/master/clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseValue.java#L916-L917)? 
IIUC, if user trying to insert [0.1, 0.2] it will throw this illegal argument exception. Similarly for other collections.

**Comment by zhicwu** [comment]
> do I still need to use `ps.setString(1, "test")` & `ps.setInt(3, 123)` ?

Yes. `input('col1 String, col2 DateTime64(3), col3 Array(String)')` was parsed(without additional network call), so the driver knew there are 3 typed parameters.

> Can I just use ps.setObject(index, obj) for any types of data for simplicity? And can ps.setObject(index, obj) handle String[] correctly in this case?

Maybe not. By default, the driver use SQL-based PreparedStatement, which will simply convert parameters to string, substitute `?` placeholders, and then send the large SQL to server. It's inefficient as it's text-based and it involves lots of string concatenation, not to mention it has problem dealing with binary values.

When you pass a timestamp/LocalDateTime to PreparedStatement, it's difficult for the driver to figure out how to format the parameter because it has no idea what the column type is - is it DateTime32 or DateTime64? If it's the latter, what's the precision?

> Besides why only 1 element array is allowed as shown [here](https://github.com/ClickHouse/clickhouse-jdbc/blame/master/clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseValue.java#L916-L917)?

Because in general `ClickHouseValue` represents a single value instead of multiple values. Those update(*) methods are just for convenience(to convert value from one type to another) and performance(especially when asm-based optimizer is available and correct update method was invoked).

> IIUC, if user trying to insert [0.1, 0.2] it will throw this illegal argument exception. Similarly for other collections.

Yes, it's expected. Keep in mind that `ClickHouseValue` is just an interface. If you are dealing with Array, it's better to use `ClickHouseArrayValue` or classes under `com.clickhouse.client.data.array` package instead.

**Comment by zheyu001** [comment]
Thanks for the details @zhicwu, really appreciate it!

**Comment by eugeniasimich** [comment]
Thanks @zhicwu!
