### ISSUE TITLE
How to parse Clickhouse select SQL.

### ISSUE THREAD

**Issue by kiwimg** [ClickHouse/clickhouse-jdbc#945]
How to parse Clickhouse select SQL.，能够得到最终select的 查询字段

ClickHouseSqlParser.jj

**Comment by zhicwu** [comment]
Hi @kiwimg, sorry it's not going to work because 1) it's not a full-featured parser as it skips parts the driver does not care about(e.g. expressions inside parenthesis); 2) it's outdated(e.g. not even support `EXCHANGE` statement); and 3) it's slow(see #615) for parsing large query. Moreover, the parser will be moved from `clickhouse-jdbc` to `clickhouse-jdbc-ext`(JDBC extensions with experimental features) in the future.

Perhaps you can take a look at https://github.com/ClickHouse/ClickHouse/tree/master/utils/antlr and enhance the parser to fit your needs.

**Comment by kiwimg** [comment]
antlr is golang ，java 如何使用呢？

**Comment by kiwimg** [comment]
Very useful, thank you very much. I know how to solve it
